### ISSUE TITLE
Docs.rs にドキュメントが生成されない

### ISSUE THREAD

**Issue by awrznc** [awrznc/GalM#3]
`v0.0.2` を公開した際にDocs.rs上でエラーが発生していた。 https://github.com/awrznc/GalM/pull/2#discussion_r417985810

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/build.rs:8:20
```

`target/`ディレクトリが見つけられなくてエラーが発生しているようだったので、ディレクトリを作成するコードを追記した。（ 2c53804 ）

これで修正できたと思ったら、 `v0.0.3` の公開時にまたエラーが発生してしまった。

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 30, kind: Other, message: "Read-only file system" }', src/build.rs:8:5
```

> https://blog.rust-lang.org/2019/09/18/upcoming-docsrs-changes.html#what-will-change
> Only the `target/` directory will be writable, and it will be purged after each build.

Docs.rsではビルド中の `target/` 以外のディレクトリへの書き込み禁止しているみたい。
ディレクトリを生成しての対応は難しそうだ。。

**Comment by awrznc** [comment]
ビルド用のコンテナイメージが公開されているっぽいので検証してみた。

1. イメージをダウンロードしてコンテナを立ち上げる。
```bash
# get container image
docker pull rustops/crates-build-env

# run
docker run --rm --memory 3221225472 -it rustops/crates-build-env bash
```
2. コンテナ内で Rust nightly をインストールする。
```bash
# install
curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y

# check
/root/.cargo/bin/cargo --version
# => cargo 1.45.0-nightly (90931d9b3 2020-04-28)
```
3. リポジトリをクローンしてくる。（gitはすでにインストール済み。ほかに必要なものがある場合はここでインストールする。ちなみにイメージの元は、現状Ubuntu18.04.4っぽいのでaptが使える）
```bash
git clone https://github.com/awrznc/GalM.git
cd GalM/
```
4. ドキュメントを生成する
```
 /root/.cargo/bin/cargo fetch
time cargo doc --no-deps
```

=> 通った

**Comment by awrznc** [comment]
実行ログに環境変数が表示されていた

> CARGO_TARGET_DIR=/opt/rustwide/target

何も指定していない場合はプロジェクトのトップディレクトリが指定されるようだ。

試しに指定して実行してみたところ

```bash
$ export CARGO_TARGET_DIR=/tmp/target && cargo build
   Compiling galm v0.0.3 (/home)
error: failed to run custom build command for `galm v0.0.3 (/home)`

Caused by:
  process didn't exit successfully: `/tmp/target/debug/build/galm-acd3253fda67a7c7/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', build.rs:8:20note: run with `RUST_BACKTRACE=1` environment variable to display a backtrac
```

logと同じエラーが表示された！

**Comment by awrznc** [comment]
`.cargo/config` に `CARGO_TARGET_DIR` を指定することができるらしいのでやってみたが、環境変数の値の方が優先されてしまうみたい。
残念。。

```
[build]
target-dir = "target"
```

**Comment by awrznc** [comment]
> https://stackoverflow.com/questions/50553370/how-do-i-use-include-str-for-multiple-files-or-an-entire-directory

おお、こんなことも可能なのか。。
なんかよさそうなので`0.0.4`でやってみる。

**Comment by awrznc** [comment]
> https://docs.rs/galm/0.0.4/galm/

うまく生成できた！:tada:
